name: flutter_cleaner_cli
description: A cross-platform CLI tool to clean Flutter build directories and free up disk space.
version: 1.1.1
repository: https://github.com/plokmij/flutter_cleaner_cli

environment:
  sdk: ^3.10.7

dependencies:
  args: ^2.6.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  flutter_cleaner: flutter_cleaner
